list = []
print("Life Before Loops!")
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
item = input("Enter the fruit: ")
list.append(item)
print(list)